<center> <h2>Algorithmic Thinking - Week 1 </h2> </center>
<center> <h3>---------------------------------------</h3> </center>

####*Video 1.1 - What is Algorithmic Thinking?*

**A. Notes**

- how do we formulate problems? we are we solving <current problem>?
- think in terms of inputs and outputs (encode the real-world problem in a computer-readable way)
- e.g. a network is probably well-represented by a graph
	- nodes conected by edges
- an algorithm is a mapping from inputs to outputs
	- usually a composition of many previously-solved general problems
- "the algorithm" and "the encoding of the algorithm" are separate things
	- go from a physical/visual/theoretical description to a code-based implementation
- the final step in the process:
	- report the results in an informative way
	
####*Video 1.2 - Class Structure*

**A. Notes**

- four two-week modules
- set of tasks:
	- learning material via videos, reading "Class Notes" and "Coding Notes"
	- graded stuff: homework (Coursera quiz), project (machine-graded), application (peer-evaluated)

####*Video 1.3 - Pseudo-Code*

**A. Notes**

- typically you use pseudo-code when describing an algorithm
- pseudo-code syntax is informal by construction
- pseudo-code is about "what", not "how"
- another search for a minimum:
	- sort, take first element

####*Video 1.4 - The small-world problem*

**A. Notes**

- small world = "unexpected node-node connections"
- "if I take two individuals, what is the probability that they are connected by some small path"
- if a network has the small-world property, information will flow through it very quickly
- look up "the Milgram experiment"...mailing letters among individuals
- given a graph, produce a "distribution of pairwise distances"
	- look at every pair of nodes, calculate the distance in "number of edges"
	- you might consider *weighting* the edges for intensity (e.g. "volume of trade", "who knows whom best")

####*Video 1.5 - Graphs and representation*

**A. Notes**

- an edge is a set of two nodes
	- directed edges = unilateral (represented as ordered pairs)
	- undirected edges = bilateral (represented as unordered pairs)
- a formalization of a graph in pseudo-Python:
	- consider a square, with vertices  0-3 representing the nodes
	- Graph G = (V,E)
	- where V is the set of nodes, E is the set of edges
	- V = {0,1,2,3}
	- E = {{0,1}, {1,2}, {2,3}, {3,0}} (unordered pairs w/ set notation)
- for a directed graph, we use tuple notation rather than graph notation for the edges
- in this course, we will not allow "parallel edges" or "self loops"
	- parallel edge = multiple edges in same direction between same nodes
	- self loop = edge from node to itself

**B. Adjacency list representation**

- think about a Python dictionary for representing edges
- for example:

```{r eval=F, engine = 'python'}
G = { 0:{1,3,4},
	1:{2,3,4}}
```

- redundancy in representation is a concern in undirected graphs, but not in directed
- now what is an adjacency *matrix*?
	- for a n-node graph, it is an n-by-n square matrix
	- if you have adjacency matrix A, then A[i,j] will be 1 if there is an edge between i and j
- the adjacency matrix of an undirected graph will be a symmetric matrix
	- for a directed graph, this is not the case
	- the matrix will be AT MOST as dense as the corresponding undirected graph...but probably more sparse
	- symmetric means A[i,j] = A[j,i]
- if the graph is sparse (e.g. in directed case), it's better to use an adjacency list
- if the graph is dense (e.g. undirected case, lots of edges), it makes more sense to use an adjacency matrix
- "two nodes are adjacent if there is an edge between them"
- in directed graphs, we have TWO definitions of "neighbor"/"adjacent nodes":
	- in-degree = the number of incoming edges
	- out-degree = the number of outgoing edges

####*Video 1.6 - Paths and distances*

**A. Notes**

- undirected: degree is the number of neighbors
- directed: measure in-degree and out-degree separately
- distance = (smallest) number of edges you have to connect over to get from one node to another
	- avg. distance = average of all unique paths
- a path of length k between nodes is a set of k-1 edges from node i to node j
- remember in directed graphs, you must also respect the direction of edges
- now we can formulate the facebook problem in a graph-theoretic sense

####*Video 1.7 - Brute Force*

**A. Notes**

- the problem: how do we calculate the degree distribution?
- the simplest algorithm (almost certainly suboptimal) is the "brute force"
	- ask ```for k = 1:10 (is there a path of k between them?)```
	- how do we determine the mximum value of k to test?
- "is there always a path of a finite length between any two nodes?"
	- no! some nodes will not be connected at all
	- given the number of nodes, we know the maximum theoretical path length
	- the max distance in an n-node graph is (n-1)
- if there is no path, the distance is infinity
- how do we check if there is a length-k path between
	- try putting other nodes between them to satisfy this
	- try every subset of (k-1) and ever permutation possible
- "brute force" = literally follows the definition of the problem to try to solve it
- brute force algorithms are easy to implement, easy to describe, easy to persuade people that they are correct representations of the problems
- the key drawback = efficiency

####*Video 1.8 - What is algorithm efficiency?*

**A. Notes**

- sometimes we are willing to sacrifice a bit of efficiency for ease of implementation
- not all correct algorithms are born equal
- two measurement dimensions: time and space
	- how long does this implementation take?
	- how much physical memory does it take?
- the choice of adjacency list vs. adjacency matrix will matter for time
- implementation is not about programming language...but more about data structures
- tradeoffs between time and space efficiency

####*Video 1.9 - Measuring Efficiency*

**A. Notes**

- time is impacted by the type of machine, the programming language
- we're interested in expressing time as a fuction of input size
- size of a graph could be:
	- number of nodes
	- number of edges
	- number of nodes and edges
- we're not concerned, technically, about the literal time (in seconds), but the growth of running time as a funciton of input size
- information = log2P = number of bits required
- we're trying to get at an answer to the question "how many operations will be performed?"
	- all operations in the algorithm have essentially fixed, independent run time

**B. Analyzing Running Time**

- three scenarios:
	1. worst case
	2. best case
	3. average
- in this course we'll focus on worst-case analysis
- worst case:
	- fix the input size and say "what type of input of this size is the worst case"

####*Video 1.10 - Efficiency of brute force distance*

**A. Notes**

- we want to reason about things like "what will force it to look at every possible option"
- in our graph distance case, the algorithm will take the longest time when there are no paths
- we make the big assumption that all small types of operations take some fixed amount of time
- the number of subsets of size k of a set of size n is n!/(n-k)!k! ... ("n choose k")
- the number of permutations of a list of n elements is n!

####*Video 1.11 - Number of steps of brute force distance*

**A. Notes**

- for loops, we need to talk about how many times they need to iterate
- the goal is to get out a formula hwich expresses runtime as a function of input size
- think carefully about what is inside of loops and how many times things are being executed
- once you have an expression in terms of n (input size), you can make that a python function and try plugging in values of n and try to map out the growth rate of the function
- the nuber of subsets of n-1 is 2^(n-1)
	- this will take "at least" exponential time
	- you can start caging things in terms of lower and uppers bounds w/o algorithm specifics