---
title: "Module 3 Graded Quiz"
author: "®γσ, Eng Lian Hu"
date: "June 8, 2016"
output: word_document
---


# Module 3 Graded Quiz

10 questions

*Correct 1/1 point*

1. In the basic economic order quantity (EOQ) model, at Q* the total annual holding cost:

- Is less than the total annual ordering cost
- **Equals the total annual ordering cost**
- Bears no necessary relationship to total annual ordering cost
- Is greater than the total annual ordering cost

*Correct 1/1 point*

2. In the basic economic order quantity (EOQ) model, a doubling of estimated annual demand would lead to:

- More than a 50% decrease in Q*
- **Less than a 50% increase in Q***
- Doubling of Q*
- No change in Q*

*Correct 1/1 point*

3. The annual demand for an item is 6,000 units. A year consists of 250 workdays. Order lead time is 4 workdays. The standard deviation of daily demand is 2 units. For a cycle service level of 98% (z=2.05), the reorder point (rounded to the nearest whole number) will be:

- 133
- **104**
- 112
- 129

*Correct 1/1 point*

4. Which of the following is most likely a reason for making a component rather than buying it?

- **Tighter control of quality**
- Access to specialized knowledge
- Inadequate capacity
- Volume based costs

*Correct 1/1 point*

5. Which of the following is not an assumption of the economic order quantity (EOQ) model?

- Demand for the product is uniform throughout the period
- Inventory holding cost is based on average inventory
- **Rate of holding cost decreases as quantity increases**
- Cost of ordering is constant

*Correct 1/1 point*

6. A company has recorded the last five days of daily demand for their only product. These values are 120, 125, 124, 128, and 133. The time from when an order is placed to when it arrives at the company from its vendor is 5 days. Using the continuous review inventory management model and no safety stock, the reorder point (ROP) is:

- 120
- **630**
- 126
- 950

1 point

7. Which of the following is not a factor impacting supply chain complexity?

- Reduced number of suppliers**3
- Increased competition**1
- Longer product life cycles
- Increased opportunities to strategically use information technology**2

*Correct 1/1 point*

8. Using the ABC classification system for inventory, which of the following is a true statement?

- The "C" items are of moderate dollar value.
- You should allocate about 15% of the dollar volume to "B" items.
- **The "A" items are of high dollar value.**
- The "A" items are of low dollar value.

*Correct 1/1 point*

9. Which of the following does not help align the incentives of companies in a supply chain?

- Trust
- Visibility
- **Optimization of each company's operations**
- Design of incentives/contracts

*Correct 1/1 point*

10. In planning for a special promotion at her restaurant, the restaurant manager orders twice the usual quantity of tilapia fish from the distributor. The distributor perceives this bump in order size as a trend of increasing demand at that restaurant and in the region, and places an even larger order with her supplier. This is a result of:

- Additive manufacturing
- Vendor-managed inventory (VMI)
- **Bullwhip effect**
- Collaborative planning, forecasting and replenishment (CPFR)

