<center> <h2>Programming for Everybody - Week 4</h2> </center>
<center> <h3>---------------------------------------</h3> </center>

####*Video 4.1 - Functions*

**A. About Dr. Chuck**

- professor at U of Michigan (Ann Arbor, MI)
- put into Slytherin!

**B. Why Functions**

- we have some set of steps that we want to store and re-use
    - writing functions makes the code much more manageable
- some languages call functions subprograms or subroutines
- writing a function in Python:

```{r eval=FALSE, engine='python'}
## Simple Greeting function

def hello(person):
    print "Hello,", person, "!"

## call it
hello('James')
```

**C. Two Types**

- built-in functions from base Python or other packages
- user-defined functions:
    - new reserved words we created
    - extensions of the language
- build a function, then "invoke" it
- things functions can do:
    - return values (to be assigned to variables)
    - alter global variables (might not "return" anything)
    - print stuff to the console
    - create new global variables
    - read from files
- functions process inputs into outputs

**D. Creating Functions**

- Python doesn't execute the code inside your ```def()``` statement until you call the function
- defining and calling functions is part of the "define and reuse" pattern
- a parameter is a variable which we use in the function definition that is a "handle" that allows the code in the function to access the arguments for a particular function invocation
    - variables that temporarily store the value of parameters
    - write conditional blocks inside the function and execute based on what arguments you get
- return values - what a function gives you back
    - take some inputs and then pass back output
    - this, in turn, is stored in a variable
- a "fruitful" function is one that produces a result (which can be passed to a variable)
- parameters are assigned to arguments left to right
    - when calling, be sure to match the number and order of arguments and parameters

**E. Void (non-fruitful) Functions**

- doesn't return a value
- print some stuff, maybe

**F. Why Use Functions?**

- organize your code into "paragraphs"
    - capture a complete thought and name it
- don't repeat yourself - make it work once and reuse it
- if something gets too long or complex, break up logical chunks and put those chunks into functions
- make a library of common stuff that you do over and over
    - you could even share this with others!
    
####*Video 4.2 - Bonus: Building Coursera, Daphne Koller*

**A. Notes**

- Daphne Koller (Stanford, Coursera)
- "education is the great equalizer"
- Andrew Ng trajectory - "let's teach the world"
- you can't use autograding to grade subjective things like short essays
    - this is where the social element of the platform becoems crucial
    - use peer-grading as a scalable solution to grading
    - in addition, peer-grading is an additional learning tool
- the community of the forums is very impactful
- in Fall of 2011:
    - median response time on forums was 22 minutes (whoa!)
- study groups grew organically
    - people took control of their own studying
    - groups formed around geography, language
    - some met physically, others communicated "in the physical space"
- Coursera recognized the value of being a "platform" (think Jeff Jarvis, What Would Google Do?)
    - users have taken over and created incredible learning experiences for each other
    - digitializing the lectures crystallizes the information for posterity
- the goal:
    - lifelong learning experience
    - learning does not have to stop when you leave high school or college
    
####*Video 4.3 - Guido Van Rossum, The Early Years of Python*

**A. Notes**

- Python developed as part of the Amoeba operating system project
    - slow to write utilities in C
- ABC was at too high level of abstraction
    - not an OOP language
- Van Rossum worked on Python at night and in free time
    - a few coworkers of his saw early progress, got excited, began to contribute
- by the end of 1990, the plan was laid out for an open source release
    - this was before "open source" had even been coined
- by luck, his management at CWI allowed open source release of Python
    - things snowballed from there
- posted to Usenet News group
    - useful positive feedback came back almost immediately
- the Unix world was much less homogeneous in the 90s
- NIST invited him to the U.S.
    - first Python workshop in Maryland in 1994

