---
title: "Lesson 1-2 Practice Quiz"
author: "®γσ, Eng Lian Hu"
date: "June 11, 2016"
output: word_document
---

# Lesson 1-2 Practice Quiz

5/5 points earned (100%)

Excellent!

*Correct 1/1 points*

1. According to the lecture, the term "cost" in managerial accounting refers to the usage of resources.

- **True**
```
Correct Response 
That is correct!
```
- False

*Correct 1/1 points*

2. Which of the following items are considered indirect costs?

- Plastic used in the production of a bottle
- *Necessary but difficult/infeasible to trace to the cost object*
```
Correct Response 
That is correct! Indirect costs are those that are difficult/infeasible to trace to the cost object. Sometimes it is feasible to trace, but cost-prohibitive to do so. Thus, they are classified as indirect costs.
```
- Wages for an assembly line worker
- Aluminum used in the production of a mug

*Correct 1/1 points*

3. All the following are examples of questions or decisions that benefit from cost behavior information EXCEPT:

- **Managing the ratio of direct to indirect costs**
```
Correct Response 
That is correct! Many decisions benefit from cost behavior information, including the determination of products' profitability, identification of an appropriate product price, and eliminating (or adding) product lines. However, the distinction between direct and indirect costs is a different framework than a cost behavior categorization.
```
- Product price change decisions
- Product line elimination decisions
- Determination of product profitability

*Correct 1/1 points*

4. Total variable cost does NOT increase with an increase in production levels

- True
- *False*
```
Correct Response 
That is correct!
```

*Correct 1/1 points*

5. Total variable costs __________ while unit variable costs ____________ with an increase in production volumes.

- Increase, decrease
- *Increase, stay constant*
```
Correct Response 
That is correct! Total variable costs increase when production volume (or the volume of some other activity) increases. Unit variable costs are assumed to stay constant over volume, within a relevant range.
```
- Increase, increase
- Decrease, stay constant

*Correct 1/1 points*

6. According to the lecture, which of the following best describes the basic formula for total cost?

- Total cost = labor costs + fixed costs
- **Total cost = fixed costs + variable costs**
```
Correct Response 
That is correct! When costs are categorized according to cost behavior, total costs are split into two categories: fixed costs and variable costs.
```
- Total cost = product costs + fixed costs + variable costs
- Total cost = fixed costs - overhead + materials costs

*Correct 1/1 points*

7. The term relevant range refers to the range in which linear patterns are valid while discussing fixed and variable costs.

- **True**
```
Correct Response 
That is correct!
```
- False

*1 point*

8. Why is it important for managers to make accurate, non-arbitrary decisions on the allocation of overhead costs?

- **Consumers will not pay a higher price**
- Management may look foolish
- **Regulations state that decisions should not be arbitrary**
```
Incorrect Response 
Unfortunately, that is not correct. Given the specialized nature of managerial accounting information, there are no related regulations. Instead, more accurate (as opposed to arbitrary) overhead cost allocation prevents poor decisions.
```
- To prevent poor decisions from being made

*1 point*

9. Total fixed costs ____________ while unit fixed costs _______________ with an increase in production volumes.

- Decrease, decrease
- *Increase, increase*
```
Incorrect Response 
Unfortunately, that is incorrect. Total fixed costs stay constant when production volume (or the volume of some other activity) increases. Unit fixed costs decrease over increasing volumes, as the same amount is "spread" over more units.
```
- **Stay constant, decrease**
- Stay constant, stay constant

*1 point*

10. Total variable costs __________ while unit variable costs __________ with an increase in production volumes.

- **Increase, stay constant**
- Increase, decrease
- Decrease, stay constant
- Increase, increase

*1 point*

11. Based on the lecture, the two main purposes of managerial accounting are to ______________.

- Discover and implement accounting rules
- **Create and publish financial statements**
- Manage and train accounting employees
- Facilitate and guide/influence decisions

*1 point*

12. Based on the lecture, which of the following groups use managerial accounting to help the organization achieve its goals?

- Suppliers, customers, other partners
- **Investors and potential investors**
- Competitors
- Managers and employees

*1 point*

13. The purpose of managerial accounting is to report the financial information of the organization to investors and creditors.

- **True**
- False

*Correct 1/1 points*

14. Direct costs refer to the cost of any materials and labor that cannot easily be traced back to the cost object.

- True
- **False**
```
Correct Response 
That is correct!
```
