<center> <h2>Principles of Computing - Week 8</h2> </center>
<center> <h3>---------------------------------------</h3> </center>

####*Video 8.1 - The Importance of Trees*

**A. Notes**

- trees are a "recursive data structure"
    - just keep applying definitiosn that take a root and children nodes
- this week, we'll think about game trees

####*Video 8.2 - Lambda*

**A. Notes**

- ```lambda``` is an anonymous function in Python
- used to simplify your code
- remember you could define a function ```square()``` and call ```map(square,data)``` to get back a list with each element of data squared
    - this requires predefining square
    - it would be quicker to do ```data_sq = map(lambda x: x**2, data)```
- let's say we want to filter a list to get only the even elements
    - you might try ```data_ev = filter(lambda val: val % 2 == 0, data)```
    
**B. How Lambda Works**

- you call ```lambda``` followed by comma-separated arguments, then a colon and the body (one expression)
- the result of the expression is the return value

####*Video 8.3 - Trees*

**A. Notes**

- trees make the code simple and clean (via recursion)
- the "one parent" rule guarantees that the trees are hierarchical

**B. Notes**

- Python code for Tree class:

```{r eval=FALSE}
"""
Python definition of basic Tree class

IMPORTANT:  Some class methods assume that instances of the Tree class
always have a single parent (or no parent for the root). See problem #8
on homework #3 for more details.
"""


class Tree:
    """
    Recursive definition for trees plus various tree methods
    """
    
    def __init__(self, value, children):
        """
        Create a tree whose root has specific value (a string)
        Children is a list of references to the roots of the subtrees.  
        """
        
        self._value = value
        self._children = children
        
        
    def __str__(self):
        """
        Generate a string representation of the tree
        Use an pre-order traversal of the tree
        """
        
        ans = "["
        ans += str(self._value)
                   
        for child in self._children:
             ans += ", "
             ans += str(child)
        return ans + "]"

    def get_value(self):
        """
        Getter for node's value
        """
        return self._value

    def children(self):
        """
        Generator to return children
        """
        for child in self._children:
            yield child
                    
    def num_nodes(self):
        """
        Compute number of nodes in the tree
        """
        ans = 1
        for child in self._children:
            ans += child.num_nodes()
        return ans
    
    def num_leaves(self):
        """
        Count number of leaves in tree
        """
        if len(self._children) == 0:
            return 1
        
        ans = 0
        for child in self._children:
            ans += child.num_leaves()
        return ans

    def height(self):
        """
        Compute height of a tree rooted by self
        """
        height = 0
        for child in self._children:
            height = max(height, child.height() + 1)
        return height

    
def run_examples():
    """
    Create some trees and apply various methods to these trees
    """
    tree_a = Tree("a", [])
    tree_b = Tree("b", [])
    print "Tree consisting of single leaf node labelled 'a'", tree_a
    print "Tree consisting of single leaf node labelled 'b'", tree_b
    
    tree_cab = Tree("c", [tree_a, tree_b])
    print "Tree consisting of three node", tree_cab
    
    tree_dcabe = Tree("d", [tree_cab, Tree("e", [])])
    print "Tree consisting of five nodes", tree_dcabe
    print 
    
    my_tree = Tree("a", [Tree("b", [Tree("c", []), Tree("d", [])]), 
                         Tree("e", [Tree("f", [Tree("g", [])]), Tree("h", []), Tree("i", [])])])
    print "Tree with nine nodes", my_tree
    
    print "The tree has", my_tree.num_nodes(), "nodes,", 
    print my_tree.num_leaves(), "leaves and height",
    print my_tree.height()

    #import poc_draw_tree
    #poc_draw_tree.TreeDisplay(my_tree)
    
             
#run_examples()
```

- interior nodes are arithmetic operators, leaf nodes are numbers

####*Video 8.4 - Illustration of Trees*

**A. Biology Example**

- biologists take observed genetic sequences and some reasoning about mutations:
    - from this, they can infer trees backwards
- trees are a powerful tool in computer science/mathematics
    - used in many other places
    - central in biology

####*Video 8.5 - Minimax*

**A. Notes**

- a game-playing strategy in which you "minimize the maximum loss"
    - do the thing that minimizes your opponent's possible outcomes
- alternate back and forth based on taking max and min
    - assume every player makes the best moves
- for something like Chess, you can't evaluate the whole game...
    - need a heuristic way to determine generally "good" positions to be in

**B. Implementation**

- when you actually do minimax, you start at the bottom
- the key idea is to think about the game as a tree
    - root of the tree is the state of the game
- best = "minimizing maximum loss"
    - force your opponent into a situation where they can do the least damage

####*Video 8.6 - Tic-Tac-Toe: Minimax*

**A. Notes**

- minimax should perform better than MC
    - in MC, we weren't search the ENTIRE game tree
- depth-first search:
    - search entire paths one at a time
    - this falls out naturally when we use recursion
- using recursion allows us to avoid actually building the tree

**B. The Mini-Project**

- it's a big tree to search
- you know the scores will always be -1, 0, 1
    - if you find 1 in a max player, you've found a global maximum...stop searching
    - same logic for -1s
    - if you don't do this, your player will be very slow
- you may not want to search all the squares
    - try to find areas of the board that trigger earlier termination sooner
- 
