<center> <h2>Principles of Computing - Math</h2> </center>
<center> <h3>---------------------------------------</h3> </center>

####*Reading - M.1 Math Expressions for Homework*

**A. Notes**

- content [HERE](https://class.coursera.org/principlescomputing1-004/wiki/math_expressions)
- Coursera's quiz system can recognize and symbolically processes math expressions
    - it can even detect equivalent answers which are in different formats
- mathematical functions recognized by coursera
    - ```abs```
    - ```arg``` (returns phase in radians of a complex number)
    - ```ceiling```
    - ```conjugate```
    - ```deg``` (converts radians to degrees)
    - ```exp```
    - ```floor```
    - ```gcd``` (2 argumetns only; otherwise, you must type is as "gcd((a,b,c,d))"
    - ```im``` (get imaginary part of a number
    - ```lcm``` (2 arguments only)
    - ```ln```
    - ```log``` (also base e, same as ln)
    - ```max```
    - ```min```
    - ```mod```
    - ```rad``` (converts degrees to radians)
    - ```re``` (get real part of a number)
    - ```root``` (2-argument, where root(a,2) is equivalent to sqrt(a))
    - ```sqrt```
    - ```sign``` (returns -1 if negative, 0 if zero, 1 if positive)
    - Trig functions: ```acos```, ```acosh```, ```acot```, ```acoth```, ```asin```, ```asinh```, ```atan```, ```atan2```, ```atanh```, ```cos```, ```cosh```, ```cot```, ```coth```, ```sin```, ```sinh```, ```tan```, ```tanh```
    - Other: ```erf```, ```binomial```
- A few additional built-ins:
    - ```Catalan``` (Catalan's constant)
    - ```E``` (note uppercase)
    - ```EulerGamma``` (Euler-Mascheroni constant)
    - ```GoldenRatio```
    - ```I``` (sqrt(-1)
    - ```J``` (sqrt(-1), same as I
    - ```nan```
    - ```oo``` (infinity)
    - ```pi```
    - ```zoo``` (complex infinity)
    
####*Reading M.2 - Functions*

**A. Notes**

- we are interested in understanding how long your program takes to run in terms of the size of the input provided to the program
- mathematical functions and Python functions are similar:
    - both have abstract definitions which must be fed arguments/parameters

**B. Polynomial Functions**

- a polynomial is an expression consisting of variables and coefficients, that involves only the operations of addition, subtraction, multiplication, and non-negative integer exponents
- a function is a polynomial function if the body of the function is a polynomial whose variables corrspond to the parameters of the function
- for example;
    - $f(x,y) = xy-x-y+1$
- the above is a polynomial in x and y
- a polynomial in one variable is a "univariate" polynomial"
- the highest exponent is the "degree" of the polynomial
- quadratic is a polynomial of degree 2

**C. Other Important Functions**

- a [rational function](http://en.wikipedia.org/wiki/Rational_function) is one whose body is the ratio of two polynomials (i.e. both numerator and denominator are polynomials)
- for example:
    - $f9x) = \frac{x^{2}}{1+x}$
- exponential functions take the form $f(x) = c^{x}$
- the logarithmic function:
    - the logarithm of a number is the exponent to which another fixed value, the base, must be raised to produce that number
    - $log_{2}(32) = 5$ because $2^{5} = 32$
- two functions are inverses if $g(f(x)) = x$
    - i.e. g() undoes whatever f() did
    
**D. Significant Digits**

- a digit is significant based on the three following rules:
    - all non-zero digits are considered significant
    - zeros appearing anywhere between two non-zero digits are significant
    - trailing zeros in a number containing a decimal point are significant

**E. Scientific Notation**

- scientific notation has two parts: a "mantissa" raised to an "exponent"
- the mantissa is usually expressed using the same number of significant digits as in the original decimal form

####*Reading M.3 - Grid Representations*

**A. Notes**

- a grid is a partition of a 2D region into a disjoint collection of cells
- grids are useful in many computation applications because they provide a convenient way to partition a geometric region in a way that can easily be modeled as a 2D data structure

**B. Indexing Rectangular Grids**

- height and width measured in number of geometric elements
- the standard convention is to refer to height first, then width
- indexing such at 0

**C. Modeling rectangular grids in Python**

- given a square, we can store the index associated with a square as the tuple (row,col) in Python
- then, we can represent some relevant property of that square as the entry ```cells[row][col]``` in the 2D list ```cells```
- use a list comprehension like this:
    - ```cells = [ [... for col in range(grid_width)] for row in range(grid_height)]```
- if you don't use ```col``` or ```row``` anywhere, Pylint won't be happy
    - might need to call these ```dummy_col``` and ```dummy_row``` 
    
####*Reading M.4.1 - Basic Probability*

**A. Notes**

- probability is a branch of mathematics associated with the analysis of random phenomena
- appearances of probability in computer science:
    - [scientific computation](http://en.wikipedia.org/wiki/Monte_Carlo_method)
    - [cryptograph](http://en.wikipedia.org/wiki/Cryptography)
    - [robotics](http://en.wikipedia.org/wiki/Motion_planning)
- terminology:
    - trial/experiment = any procedure that can be infinitely repeated and has a well-defined set of possible outcomes, known as the sample space
    - if the sample space is finite, each outcome can be assigned a number between zero and one that corresponds to the likelihood of that particular otucome occurring
    - this number is the "probability" associated with the outcome.
    - probabilities sum to 1
- the probabilities associated with outcomes of a trial are said to be uniformly distributed if these probabilities all have equal value
- an event is a set of outcomes of a trial
- the probability of an event is the sum of the probabilities associated with its set of outcomes

####*Reading M.4.2 - Expected Value*

**A. Notes**

- the expected value = the mean
    - the value we expect if we choose one sample at random
- the expected value of a test is a weighted average of its outcomes, with outcomes weighted by their probability

####*Reading M.5.1 - Enumeration*

**A. Notes**

- "given a set of outcomes, a standard problem in combinatorics is to enumerate all possible sequences of outcomes formed by repeatedly choosing an outcome from the set"
- [this program](http://www.codeskulptor.org/#poc_enumeration.py) computes the set of all possible sequences of outcomes of a specified length using the function ```gen_all_sequences```

**B. Sorted Sequences of outcomes**

- in Yahtzee, ordering is irrelevant
- sorting sequences might make it easier to compare equivalent sets
- "your Yahtzee mini-project will use this idea and represent Yahtzee hands as a sorted tuple of die values to avoid having multiple representations for the same Yahtzee hand"
- these types of applications will be perfect for the Python "set" structure

**C. Applications to Probability**

- in many applicatiosn in probability, we are interested in enumerating the sequences of outcomes associated with a sequence of trials
- for a sequence of independent trials, the probability of a particular sequence of outcomes is the product of the probabilities associted with each individual outcome

####*Reading M.5.2 - Permutations and Combinations*

**A. Notes**

- the factorial of a number is the product of it and all positive integers lower than it
- in Python:

```{r eval = FALSE}
import math
print math.factorial(6)
```

**B. Permutations**

- "given a set of outcomes, a sequence of outcomes of length n with no repetition is a permutation of size n of this set"
- ordering matters
- no repeats
- common question --> "how many permutations of length n are possible given a set of outcomes of size m"?
- m x (m-1) x ... x (m-n+1)
- In other words, you have $\frac{m!}{(m-n)!}$ permutations possible

**C. Combinations**

- combinations are like permutations, except the order is irrelevant
- Yahtzee hands are combinations of 5 6-sided dice
- "how manay combinations of length n are possible given a set of oucomes of size m"?
    - $\frac{m!}{(m-n)!n!}$
    - "m choose n"
    
####*Reading M.6.1 - Arithmetic Sums*

**A. Notes**

- an airthmetic sum is the operation of adding a sequence of numbers
- common sums:
    - the sum of n n+1 times = (n+1)n
    - the sum of 0 + 1 + 2...n is the "triangular sum", a quadratic of the form 1/2(n+1)n
    - the geometric sum of 2^0 + 2^1 + 2^2...2^n = 2^(n+1)-1
    - the harmonic sum (1 + 1/2 +1/3....) is approximately log(n) + gamma, where gamma is some small constant
    
####*Reading M.6.2 - Logarithms and Exponentials*

**A. Notes**

- if exp(n) = m, log(m) = n
    - natural log and exp() are inverses of each other
- exp(n+m) = exp(n)exp(m)
- log(nm) = log(n) + log(m)

**B. Log/Log Plotting**

- think about the problem $y = ax^{n}$
    - $log(y) = log(ax^{n})$
    - $log(y) = log(a) + nlog(x)$
- strategy:
    - plot the datapoints (log(x),log(y) and check whether these data points lie near a straight line
    - if they do, the original data points (x,y) lie near polynomial function. Moreover, the degree of this polynomial is simply the slope of this line

####*Reading M.6.3 - Growth Rates and Functions*

**A. Notes**

- "...the running time of a program may depend on many factors such as the power of computer's processor, the speed of its operating system, and the performance of any encironment that runs the computation (like a web broswer). However, if the running time of a program grows at an exponential rate, the processing power of even the fastest computers will be quickly overwhelmed"

**B. Techniques for comparing growth rates**

- two polynomial functions f(n) and g(n) growth at the same rate if they have the same degree. Lower degree terms in these functions have no effect on relative growth rates
- if the degree of the polynomial function f(n) is higher than the degree of g(n), f(n) grows faster than g(n). Conversely, if the degree of f(n) is lower, f(n) grows slower than g(n)
- the function log(n) growth faster than the constant function 1 and slower than the linear function n. The nlog(n) grows faster than n and slower than n^2
- any exponential function a^n with a>1 grows faster than any polynomial function. The factorial function n! grows faster than a^n and, consequenctly, faster than any polynomial function

**C. An example from ball physics**

- if f(n)/g(n) tends to a positive constant, the two functions must be of the same degree

####*Reading M.7.1 - Breadth-First Search*

**A. Notes**

- BFS is a search strategy that models the growth of a fire in which the search proceeds radially outward from the initial search locations
- "at any point in this search, breadth-first search processes all of the cells on the current boundary of the search before processing any new cells added to the search boundary"
- during the depth-first search, search propagates outward in one preferred direction until it can no longer proceed in that direction

**B. Graphs**

- a \textbf{graph} is "a data structure that consists of two sets of objects: a collection of *nodes* and a collection of *edges* that link pairs of neighboring nodes"

####*Reading M.8.1 - Recurrence Relations*

**A. Recurrence Relations**

- a recurrence relation is a set of equations that defines a function of one or more numbers recursively
- initial values are given, with larger values defined as a recursive function of smaller values
- many recursive relations map to simple closed form functions

**B. Modeling the behavior of recursive programs using recurrences**

- "one call to a binary search on a list of size n requires one comparison plus the number of comparisons required to perform a binary search on a list of size n/2, f(n/2)
- there are 2^n n-bit binary numbers

**C. Solutions to Common recurrences**

- $f(n) = n \ f(n - 1) \quad \quad \rightarrow \quad f(n) = n$
- $f(n) = f(n - 1) + n \quad \rightarrow \quad f(n) = \frac{1}{2}n (n+1)$
- $f(n) = 2 f(n - 1) \quad \quad \rightarrow \quad f(n) = 2^{n-1}$
- $f(n) = n \ f(n - 1) \quad \quad \rightarrow \quad f(n) = n!$
- $f(n) = f(\frac{n}{2}) + 1 \quad \quad \ \rightarrow \quad f(n) \approx \log_2(n)+ 1$
- $f(n) = f(\frac{n}{2}) + n \quad \quad \ \rightarrow \quad f(n) \approx 2n - 1$
- $f(n) =2 f(\frac{n}{2}) \quad \quad \quad \ \rightarrow \quad f(n) \approx n$
- $f(n) =2 f(\frac{n}{2}) + 1 \quad \quad \rightarrow \quad f(n) \approx 2 n - 1$
- $f(n) =2 f(\frac{n}{2}) + n \quad \quad \rightarrow \quad f(n) \approx n (\log_2(n) + 1)$

####*Reading M.9.1 - Trees*

**A. Notes**

- tree = hierarchical data structure
- applications of trees:
     - searching, sorting, modeling biological processes, arithmetic expressions
     
 **B. Basic definition and display**
 
 - "rooted tree" = a collection of nodes and edges that can be organized recursively:
    - a roote note has a value and a list of references to subtrees
    - root nodes of subtrees are children of the root node for the original tree
    - each subtree has exactly one parent
- in graph theory, an "unrooted" tree is a graph with n nodes and n-1 edges, with the property that any pair of nodes is connected by a sequence of edges

**C. Structural Properties of Trees**

- nodes are classified based on their number of children
- a node withotu children is a "leaf node"
- nodes with one or more children are internal/interior nodes
-  binary trees = all nodes have two or fewer children
    - full binary trees - binary trees in which all internal nodes have exactly two nodes
    - full binary trees arise in search and sort

####*Reading M.9.2 - Minimax*

**A. Notes**

- consider a tic-tac-toe board, where parent nodes represent game states and children represent one move beyond that game state
- key assumption behind minimax --> both players will make the best move
- arranging game states into a tree, you search the tree (using simple min/max rules) and look for paths with the most favorable scores

####*Reading M.10.1 - Invariants*

**A. Notes**

- building blocks for reasoning about whether or not your program works are logical conditions that consist of Boolean expression involving values in the program
- an \textbf{invariant} is a condition that is guaranteed to be true at a specified set of points during the execution of a program
- a coding philosophy:
    - "that the invariant is true prior to the fragment. Write a code fragment that moves the computation towards the final answer and ensures that the invariant is again true at the end of the fragment.
- invariants might also be used to reason about the correctness of recursive programs
- you could also use invariants explicitly in classes to check their behavior

