<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2008

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://service.existing.training.mk.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:standard="http://e-commerceANDm-commerce/ShoppingStandards" xmlns:mesdef="http://org.mk.traininggmail.com/MessageDefinitions" exclude-result-prefixes="tns xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/tns:processOrderResponse">
		<mesdef:requestOrderResponse>
			<Order xmlns="">
				<xsl:for-each select="return">
					<xsl:for-each select="orderKey">
						<OrderKey>
							<xsl:value-of select="."/>
						</OrderKey>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="return">
					<xsl:for-each select="orderHeader">
						<OrderHeader>
							<xsl:for-each select="salesOrganization">
								<SalesOrganization>
									<xsl:value-of select="."/>
								</SalesOrganization>
							</xsl:for-each>
							<xsl:for-each select="dateOfPurchase">
								<DateOfPurchase>
									<xsl:value-of select="."/>
								</DateOfPurchase>
							</xsl:for-each>
							<xsl:for-each select="customerNumber">
								<CustomerNumber>
									<xsl:value-of select="."/>
								</CustomerNumber>
							</xsl:for-each>
							<xsl:for-each select="paymentMode">
								<PaymentMethod>
									<xsl:value-of select="."/>
								</PaymentMethod>
							</xsl:for-each>
							<xsl:for-each select="purchaseOrderNumber">
								<PurchaseOrderNumber>
									<xsl:value-of select="."/>
								</PurchaseOrderNumber>
							</xsl:for-each>
						</OrderHeader>
					</xsl:for-each>
				</xsl:for-each>
				<standard:Cart>
					<xsl:for-each select="return">
						<xsl:for-each select="products">
							<Item>
								<xsl:for-each select="name">
									<Name>
										<xsl:value-of select="."/>
									</Name>
								</xsl:for-each>
								<xsl:for-each select="itemNumber">
									<ItemNumber>
										<xsl:value-of select="."/>
									</ItemNumber>
								</xsl:for-each>
								<xsl:for-each select="quantity">
									<Quantity>
										<xsl:value-of select="."/>
									</Quantity>
								</xsl:for-each>
								<xsl:for-each select="pricePerUnit">
									<PricePerUnit>
										<xsl:value-of select="."/>
									</PricePerUnit>
								</xsl:for-each>
								<xsl:for-each select="description">
									<Description>
										<xsl:value-of select="."/>
									</Description>
								</xsl:for-each>
							</Item>
						</xsl:for-each>
					</xsl:for-each>
				</standard:Cart>
				<xsl:for-each select="return">
					<xsl:for-each select="creditCard">
						<standard:CreditCard>
							<xsl:for-each select="type">
								<Type>
									<xsl:value-of select="."/>
								</Type>
							</xsl:for-each>
							<xsl:for-each select="number">
								<Number>
									<xsl:value-of select="."/>
								</Number>
							</xsl:for-each>
							<xsl:for-each select="expiryDate">
								<ExpiryDate>
									<xsl:value-of select="."/>
								</ExpiryDate>
							</xsl:for-each>
							<xsl:for-each select="name">
								<Name>
									<xsl:value-of select="."/>
								</Name>
							</xsl:for-each>
							<xsl:for-each select="amount">
								<Amount>
									<xsl:value-of select="."/>
								</Amount>
							</xsl:for-each>
							<xsl:for-each select="dateOfPurchase">
								<DateOfPurchase>
									<xsl:value-of select="."/>
								</DateOfPurchase>
							</xsl:for-each>
						</standard:CreditCard>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="return">
					<xsl:for-each select="description">
						<description>
							<xsl:value-of select="."/>
						</description>
					</xsl:for-each>
				</xsl:for-each>
			</Order>
		</mesdef:requestOrderResponse>
	</xsl:template>
</xsl:stylesheet>
