<center> <h2>Programming for Everybody - Week 7</h2> </center>
<center> <h3>---------------------------------------</h3> </center>

####*Video 7.1 - Files*

**A. Intro to Files**

- instruction comes into the CPU, variables stored in RAM
- programs sit in ram and ping the CPU
- so far, we've only worked in RAM and with the CPU
- now it's time to escape and move out to secondary memory ("disk"), using files
    - permanent media

**B. File Processing**

- we'll work only with text files
- the focus of this course is working with text
- before we can read the contents of the file we must tell Python which file we are going to work with
    - ```open()``` returns a "file handle" used to manipulate the file
    - ```open(filename, mode)```
- mode is optional and should be 'r' if we are planning on reading the file and 'w' if we are going to write to the file
- the act of opening it is NOT reading the data into RAM
    - it's just opening a connection with the file
- when files are missing you will get a traceback error

**C. The newline Character**

- we use a special character to indicate when a line ends called the "newline"
- we represent it as "\\n" in strings
- newline is still one character (not two)

**D. File Processing**

- think about a text file as a sequence of lines
- mentally visualize the files with "newline" punctuating the end of each line

**E. File Handle as a Sequence**

- a file handle open for read can be treated as a sequence of streings where each line in the file is a string in the sequence
- we can use the for statement to iterate through a sequence
- remeber - a sequence is and ordered set
    - i.e. this is a definite loop
- you could read the entire file into RAM (be careful!):

```{r eval=F, engine='python'}
fhand = open('mbox-short.txt')
inp = fhand.read() # read it all in
```

- inp above will be a single string variable with all the lines in it, concatenated by newlines

**F. Searching Through a File**

- use the string method ```startswith()``` to select certain lines
- using ```rstrip()``` will strip whitespace AND newline characters
    - this will take off the newlines and prevent them from screwing you up
- when you search, you might consider using ```continue``` to skip uninteresting lines
- consider using the ```in``` operator to search within lines
    - when used with strings, you could find out if some substring is inside your string!
    - e.g. ```if "@" in line:```

**G. Missing Files**

- consider using the try/except to handle the possibility of missing files or bad file names being passed to your program

####*Video 7.2 - Bonus: Gordon Bell, Building Blocks of Computing*

**A. Notes**

- emeritus research in computer science at Microsoft
- initially built tape-controlled computer units
- this dude is awesome
- builder of the PDP1
- when you first build something, you need to keep it flexible:
    - hard to know, a priori, how your component will be used
- said another way ... "build something hackable so people can do cool stuff"