CREATE TABLE ALBUMS
  (ID INTEGER NOT NULL,
   NAME VARCHAR2(250) NULL,
   ARTIST VARCHAR2(250) NULL,
   ANNUM INTEGER,
   COST INTEGER,
   ARTISTDETAILS_ID INTEGER NULL);
ALTER TABLE ALBUMS
  ADD CONSTRAINT PK_ALBUMS PRIMARY KEY (ID);


 INSERT INTO ALBUMS (ID, NAME , ARTIST , ANNUM ,COST)
	VALUES ('1','ANIMALS','PINK FLOYD','1999','30');
 INSERT INTO ALBUMS (ID, NAME , ARTIST , ANNUM ,COST)
	VALUES ('2','DEAD MAN WALKING','NUSRAT FATEH','2006','45');
 INSERT INTO ALBUMS (ID, NAME , ARTIST , ANNUM ,COST)
	VALUES ('3','WISH TOU WERE HERE','PINK FLOYD','2005','28');
 INSERT INTO ALBUMS (ID, NAME , ARTIST , ANNUM ,COST)
	VALUES ('4','BAMBOLEO','GIPSY KINGS','2006','27');
COMMIT;

