<center> <h2>Principles of Computing - Week 1</h2> </center>
<center> <h3>---------------------------------------</h3> </center>

####*Video 0.1 - Beyond CodeSkulptor*

**A. Notes**

- go to Python.org and download python for use on your machine
- not much active development in Python 2 at this point

**B. Other Packages**

- [Python Modules](https://wiki.python.org/moin/UsefulModules#GUI)
- [Game Libraries](https://wiki.python.org/moin/PythonGameLibraries)

**C. Using Global Variables**

- in general, using global variables is a bad idea
    - only works for moderate-sized programs
- global variables become a huge problem as your programs get large
- maybe think about a game-state class:
    - 1 global variable for the state
    - within that, methods to set all the other stuff

####*Video 1.1 - Principles of Computing*

**A. Notes**

- IIPP is built on an introductory course at Rice
- the goal is to be good enough at programming that in the Algorithmic Thinking class, "the programming won't get in the way"
- "I came to Computer Science because I enjoyed the interplay between mathematics and building things"
- program might be the least important skill in computer science
    - the hard problem is turning a problem into a specification

####*Video 1.2 - Introduction*

**A. Objecives**

- learn some computer science - specific mathematics
- don't just "sit down and start coding"
- learn how to be a good programmer
    - move from "some solution" to "good solution(s)"
- this is more about computer science in the abstract than programming in the specific
- we won't use the interactive techniques or GUIs in this course
    - more about internals

**B. Structure of the class**

- short, targeted video lectures
- homework problems (will take a bit of time)
    - Coursera quiz format
    - there will be math, programming
- mini-projects
    - programming assignment (100-200 lines of code to solve some problem)
- there are "Coding Notes" and "Math Notes" to help you out
- we will use CodeSkulptor again in this course
    - runs Python 2.6
    
**C. A Few Other Things**

- mini-projects will be machine graded
- programming style will be strictly enforced (and graded!)

####*Video 1.3 - Required Python Knowledge*

**A. Notes**

- see the [Required Python Knowledge](https://class.coursera.org/principlescomputing1-004/wiki/view?page=python_knowledge) page
- see the [Solitaire Mancala page](https://class.coursera.org/principlescomputing1-004/wiki/view?page=mancala)
    - this is a practice mini-project to see if you know what you need to succeed in this class

**B. Math Phobia**

- "when it comes to math, there is no substitute for practice" - Bill Nye
- "the science part of computer science is math" - Joe Warren
- math helps you to go from being a programmmer to a computer scientist

####*Video 1.4 - Coding Style*

**A. Notes**

- in any large-scale software development project, there will be style guidelines
- this class is "Principles of Computing", not "intermediate Python"
- the goal here is a high standard of readability
- one of the keys...make your errors more obvious
- make it easier to collaborate
- in small programs, you can get away with not having structure

**B. Style Guidelines**

- see documentation for this class's guidelines [here](https://class.coursera.org/principlescomputing1-004/wiki/view?page=style_guidelines)
    - enforce with [Pylint](http://www.pylint.org/)
- documentation strings don't tell you HOW the code is doing something, but WHAT specifically it is doing
- a string is not a comment! Don't use a string as a comment
- variables shold have variable names
    - classnames should not use underscores, instead use capitalization
    - variables should be all lower-class
- do not use global variables
    - only constants in all upper-case
- class fields should not be publicly accessible
    - only interact with the class via methods

**C. Why Do This**

- coding style forces you to think about structure
- style agreement encourages collaboration

####*Video 1.5 - Python Modules*

**A. Notes**

- in real development, you like to have bits of code in different files ("modules")
- [module example](http://www.codeskulptor.org/#examples_modimport.py)  
    - need to be read in with an "import" statement
- the ```dir()``` function gives you a list of functions and constants inside a module
- you can use "as" in an import statement to change how you reference things
    - e.g. ```import examples_module as example```

**B. Importing CodeSkulptor Modules**

- given a CodeSkulptor URL, you can import it as follows

```{r eval=FALSE, engine='python'}
url = "http://www.codeskulptor.org/#user40_vLHCY2wZ8jVPuLS.py"

#Import module
import user40_vLHCY2wZ8jVPuLS as mymodule
print mymodule.SOMECONSTANT
```

**C. Renaming with "as"**

- pretty much every program you write will have some import statement(s)
- don't rename gratuitously
    - only do it when renaming would increase clarity
    
####*Video 1.6 - Machine Grading: OwlTest*

**A. Notes**

- the machine grader will perform testing and give you some feedback
- there will always be an "OwlTest" link in the "testing your code" part of the minimproject description
- OwlTest does NOT submit anything to Coursera
    - you need to go to Coursera and submit your code to get an actual grade (on the mini-project page)
- CourseraTest is almost identical to OwlTest
- there can be a several-hour delay in grade transmission to Coursera from Courseratest
    - if you get feedback in CourseraTest, you're good...it will get there eventually
    
####*Video 1.7 - Assignments*

**A. Notes**

- the homework is to help you practice conceptual material
- mini-project is about putting that material into practice
- homeworks will be done with Coursera Quiz infrastructure, mini-projects in machine grader

**B. 2048 (Merge) Instructions**

- [project instructions](https://class.coursera.org/principlescomputing1-004/wiki/view?page=2048_(Merge))

**C. Deadlines**

- you can submit with late days to avoid penalties
- there is a "hard deadline" and you cannot submit at all past that
- be aware of the deadlines
- 