---
title: "Lesson 2-2 Practice Quiz"
author: "®γσ, Eng Lian Hu"
date: "June 11, 2016"
output: word_document
---

# Lesson 2-2 Practice Quiz

*5/5 points earned (100%)*

**Excellent!**

*Correct 1/1 points*

1. Cost of goods sold is comprised of all the following parts EXCEPT:

- Direct labor
- Direct materials
- **Selling expenses**
```
Correct Response 
That is correct! Selling expenses are not product costs, and thus would be included in "other expenses" (and not in cost of goods sold).
```
- Overhead

*Correct 1/1 points*

2. Based on the lecture, using absorption costing (required by financial accounting), a manager can decrease reported cost of goods sold by:

- Decreasing production levels
- **Increasing production levels**
```
Correct Response 
That is correct! All else equal (including units sold), higher production levels leads to lower fixed costs allocated to units sold (and more fixed costs reflected as inventory on the balance sheet). Thus, reported cost of goods sold is less when a manager increases production levels.
```
- Increasing selling price
- Decreasing selling price

*Correct 1/1 points*

3. Absorption costing is NOT required for financial accounting purposes but is required for managerial reporting purposes.

- True
- **False**
```
Correct Response 
That is correct! Absorption costing is required for financial accounting purposes.
```

*Correct 1/1 points*

4. In a manufacturing setting, gross margin is Revenue minus all the following, EXCEPT:

- **Other expenses**
```
Correct Response 
That is correct! Gross margin is Revenue minus Cost of Good Sold, which includes the costs of direct materials, direct labor, and overhead associated with units sold. Other expenses are subtracted from gross margin to yield operating profit (or income before taxes).
```
- Overhead
- Direct labor
- Direct material

*Correct 1/1 points*

5. Brown Company manufactures and sells pianos.

The following information is available for its single model piano, of which 0 were in inventory at the beginning of the period, 1,000 were manufactured completely. Of those manufactured during the period, 500 have been sold, and 500 remain in finished goods inventory.

Selling price (per unit) - $6,000
Variable costs (per unit)

- Materials - $2,000
- Labor - $1,000
- Selling - $500

Fixed Costs (total)

- Manufacturing - $90,000
- Selling - $25,000

Given the information above what is the cost of goods sold for the period?

- $1,500,000
- **$1,545,000**
```
Correct Response 
That is correct! Brown Company's cost of goods sold would be calculated as follows: Direct materials: 2,000 per unit x 500 units sold = $1,000,000 Direct labor: 1,000 per unit x 500 units sold = $500,000 Overhead (fixed): 90,000/1,000 units manufactured = $90 per unit; $90 per unit x 500 units sold = $45,000 Total cost of good sold: $1,000,000 + 500,000 + 45,000 = $1,545,000 Variable and fixed selling costs are not included in cost of goods sold, and thus are excluded from the calculation.
```
- $1,820,000
- $1,590,000

